language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  
  # Image building
  
  # Docker compose 
  # Remove unused and dangling images
  # - docker image prune --all

  # - docker-compose -f docker-compose-build.yaml build --parallel

  # Individual docker build commands
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  #image tagging
  - docker tag udagram-api-feed jempitman/udagram-api-feed:latest
  - docker tag udagram-api-user jempitman/udagram-api-user:latest
  - docker tag udagram-frontend jempitman/udagram-frontend:local
  - docker tag reverseproxy jempitman/reverseproxy:latest

after_success:
  #login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  #push images to DockerHub
  - docker push jempitman/udagram-api-feed:latest
  - docker push jempitman/udagram-api-user:latest
  - docker push jempitman/udagram-frontend:local
  - docker push jempitman/reverseproxy:latest